create table APPS_LEADER_LOCK
(
    LOCK_KEY     VARCHAR2(36)  NOT NULL,
    REGION       VARCHAR2(100 ) NOT NULL,
    CLIENT_ID    VARCHAR2(36) NOT NULL ,
    CREATED_DATE TIMESTAMP(6) NOT NULL,
    constraint PK_VQI_REQUEST_REPORT_LEADER_L
        PRIMARY KEY (LOCK_KEY, REGION)
);

commit ;
