create table SHASHI_LEADER_LOCK
(
    LOCK_KEY     VARCHAR2(36)  NOT NULL,
    REGION       VARCHAR2(100 ) NOT NULL,
    CLIENT_ID    VARCHAR2(36) NOT NULL ,
    CREATED_DATE TIMESTAMP(6) NOT NULL,
    constraint PK_VQI_REQUEST_REPORT_LEADER_L
        PRIMARY KEY (LOCK_KEY, REGION)
);

CREATE TABLE INT_RETRY_METADATA
(
    SOURCE_DIR             VARCHAR2(255) NOT NULL,
    FILE_UUID              VARCHAR2(36) NOT NULL,
    INCOMING_FILES_STATUS  VARCHAR2(20) NOT NULL,
    INCOMING_FILES_CHANNEL VARCHAR2(20) NOT NULL,
    CONSTRAINT PK_INT_RETRY_METADATA PRIMARY KEY (SOURCE_DIR, FILE_UUID)
);

commit ;
